apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate    
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
      - name: capstone
        image: arumdev/capstone:v1.2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000